### ISSUE TITLE
Do not default to show a dictatorship country as default option in select

### ISSUE THREAD

**Issue by marcushultgren** [xz/new.css#18]
Alphabetical order makes more sense, or just about any country actually does

**Comment by 3x** [comment]
Will be fixed in 1.1.0. Might just change them to something generic, like favorite ice cream flavors.

**Comment by 3x** [comment]
Fixed here- https://github.com/xz/new.css-site/commit/596dd5a254cb085de18bbe5e4b3a946d463b4c1b
