### ISSUE TITLE
Fix header width on Safari (13.0.4) and Chromium (78.0.3882.0) / Chrome

### ISSUE THREAD

**Issue by jeff-kroot** [xz/new.css#2]
On Safari 13.0.4, the following is rendered on newcss.net:

![image](https://user-images.githubusercontent.com/65391860/82199972-b12f3e80-98fe-11ea-8e53-9f4f66755834.png)

Also on Chromium (78.0.3882.0) / Default Chrome:

<img width="1806" alt="image" src="https://user-images.githubusercontent.com/65391860/82200087-dcb22900-98fe-11ea-9f76-7ba510d40b0b.png">

Comparing this to Firefox (76.0.1):

![image](https://user-images.githubusercontent.com/65391860/82200202-02d7c900-98ff-11ea-9e81-9bb81ca40df8.png)

I think Firefox is how it's supposed to look.

**Comment by ThomasAndrewMacLean** [comment]
[this PR](https://github.com/xz/new.css/pull/1) fixes this bug.

**Comment by 3x** [comment]
@ThomasAndrewMacLean's PR #1 fixed this. Thanks for your help!
