### ISSUE TITLE
Hard to distinguish form fields

### ISSUE THREAD

**Issue by Zegnat** [xz/new.css#21]
I almost didn’t notice the form fields in [the demo](https://newcss.net/demo/). When the form fields are not focussed in the browser they have no outline/border and are only distinguished from the website by their background colour. But the element background colour is extremely close to the page background colour.

| Mode | Page Background | Element Background | Contrast Ratio |
| --- | --- | --- | --- |
| Dark | `#000000` | `#111111` | 1.11 |
| Light | `#FFFFFF` | `#F6F8FA` | 1.06 |

There should be some form of form element indication in place at a higher contrast. Possibly just the border around it.

**Comment by 3x** [comment]
:+1: Will be fixed in 1.1.0.
