### ISSUE TITLE
Link for adding the stylesheet is not here

### ISSUE THREAD

**Issue by lucas-deangelis** [xz/new.css#27]
Thanks for creating and sharing new.cs!

There's a issue on https://newcss.net/usage. The code that you're supposed to copy to add new.css to your website is invisible. Here's what it looks like in Chrome:

![toto](https://user-images.githubusercontent.com/55180995/82451292-11181780-9aae-11ea-987a-2e1bb16eb343.png)

By inspecting the page, I saw that the two links are not quoted text, which the HTML in 1. is, and I think it might be the issue.

**Comment by 3x** [comment]
Good catch, thanks. Fixed in https://github.com/xz/new.css-site/commit/3666d03f3e52d0cece16ac0f851d1350a22b1f6c.
