### ISSUE TITLE
IE support?

### ISSUE THREAD

**Issue by h0rhay** [xz/new.css#29]
Is this supposed to work in IE11?

![bs_win10_IE_11 0 (1)](https://user-images.githubusercontent.com/2151724/82651513-2c9d3280-9c14-11ea-8b44-1d69b817cae2.jpg)

**Comment by 3x** [comment]
new.css wasn’t designed to have IE support, and it’s not likely it will be added in the future. If there’s enough interest, it would be possible to make a fork with IE support, but it won’t be added to master.
