### ISSUE TITLE
Dark / light theme switcher instead of 'prefers-color-scheme'

### ISSUE THREAD

**Issue by xcartmods** [xz/new.css#34]
Just a suggestion...

https://codepen.io/xcartmods/pen/OJyYBoN

**Comment by gaffling** [comment]
Nice idea, but please let us use a pure CSS solution without JS

**Comment by 3x** [comment]
Nice! Might be something good to add on the demo page, but as @gaffling said, there are no plans to use anything but HTML/CSS, so it won't be implemented into the new.css code.

**Comment by mr-karan** [comment]
It might still be worthwhile to distribute `light.css`, `dark.css` and `auto.css`. Pretty much like how [water.css](https://watercss.kognise.dev/) does. I don't wanna use `prefers-color-scheme` because I want my site to look consistent across everywhere.
