### ISSUE TITLE
Any tips to get tables looking nicer?

### ISSUE THREAD

**Issue by kaihendry** [xz/new.css#38]
https://natalian.org/2020/06/09/Games_for_a_four_year_old/

Not sure why this is happening to **score**:

![image](https://user-images.githubusercontent.com/765871/84153740-d8f66a00-aa98-11ea-8a86-2c167d66aff0.png)

**Comment by xcartmods** [comment]
```
<th style="white-space:nowrap">Score</th>
```

/me runs for cover

**Comment by 3x** [comment]
Going to close this issue as it looks like it's been solved. If you have any reccomendations of how to improve native support, please open another issue, I'd be glad to see how to make forms preform better automatically!

**Comment by Bauke** [comment]
This happens because `word-break: break-word` is set on `body`. Adding `word-break: initial` to `table` would make this work properly for tables and still keep the word break for everywhere else.
