### ISSUE TITLE
<blockquote> is hard to see in dark mode

### ISSUE THREAD

**Issue by alexislefebvre** [xz/new.css#58]
Light mode:

> ![image](https://user-images.githubusercontent.com/2071331/102110215-2c28eb00-3e35-11eb-81af-ab60f66bfb86.png)

Night mode:

> ![image](https://user-images.githubusercontent.com/2071331/102110278-3cd96100-3e35-11eb-8dcf-0996a079b24c.png)

The background of `<blockquote>` is too dark in dark mode.

**Comment by Atlas7005** [comment]
Do you mean it's hard to see in light mode?
Otherwise, this issue doesn't really make sense. Since it looks nice in Night mode.

If you mean Light mode, then I agree. You can fix this on your own site by applying your own background-color in your own CSS, at least until it is fixed by the devs.

**Comment by alexislefebvre** [comment]
I can see the blockquote on my phone. It looks like it's due to my settings on the computer's screen.

**Comment by alexislefebvre** [comment]
On my computer, the blockquote was too dark to distinguish it from the black background.
